export const SAVE_VIDEO_URL_TIME = 'SAVE_VIDEO_URL_TIME';
export const SAVE_VIDEO_URL_ELAPSED_TIME = 'SAVE_VIDEO_URL_ELAPSED_TIME';
export const SAVE_VIDEO_URL = 'SAVE_VIDEO_URL';
export const TIMEOUT_REQUESTED_TYPE = 'TIMEOUT_REQUESTED_TYPE';
